### PR TITLE
Update soar-production-propose.sublime-snippet

### PR DESCRIPTION
**Pull request by SimonSword**

### CODE REVIEW

**Comment by SimonSword** [comment]
Little Bugfix

**Comment by garfieldnate** [comment]
Thanks Simon. Are you interested in having commit rights for this repo? I haven't developed it or used Soar in quite a while.

**Comment by SimonSword** [comment]
Hi Nathan, that would be great! Nevertheless you have the most up-to-date Soar plugin ;)
Seems like I'm going to use Soar for my PhD-Project, so I'll use it heavily.

**Comment by garfieldnate** [comment]
Heh, yeah I'm pretty sure it's the only Sublime plugin for Soar:) I look forward to following your PhD work! Commit rights added.

**Pull request merged**
